import React, { useEffect } from 'react';
import { motion } from 'framer-motion';
import { ArrowLeft, Users, Video, Map, Info, CheckCircle2, Activity, Zap } from 'lucide-react';

interface Pillar6Props {
  onBack: () => void;
}

const Pillar6: React.FC<Pillar6Props> = ({ onBack }) => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const serviceModules = [
    {
      id: 'MOD_A',
      title: 'Internal Media Engine',
      desc: 'We transform boring SOPs and safety documentation into a private "Company Spotify" playlist using AI voice cloning. Your team learns while commuting or working.',
      icon: Users
    },
    {
      id: 'MOD_B',
      title: 'Micro-Learning Matrix',
      desc: 'High-velocity, 60-second video training modules generated by AI Avatars. TikTok-style instructions that staff actually watch and retain.',
      icon: Video
    },
    {
      id: 'MOD_C',
      title: 'Visual Intelligence Factory',
      desc: 'Converting text-heavy manuals into intuitive infographics and wall-mounted decision trees. One image = 1,000 words of clarity.',
      icon: Map
    },
    {
      id: 'MOD_D',
      title: 'The Adoption Analyst',
      desc: 'A 24/7 internal support agent trained on your unique business protocols. It answers "How do I do X?" instantly so managers don\'t have to.',
      icon: Info
    }
  ];

  const sprintRoadmap = [
    { day: '01', title: 'Friction Audit', task: 'Identifying the usage gap and tech-rejection bottlenecks.' },
    { day: '02', title: 'Cloning & Scripting', task: 'Expertise extraction and AI voice/video avatar setup.' },
    { day: '03-04', title: 'Production', task: 'Manufacturing the Visual Factory and Media Engine assets.' },
    { day: '05', title: 'Deployment', task: 'Live system integration and team gamification protocols.' }
  ];

  const revealVariants = {
    hidden: { opacity: 0, y: 30 },
    visible: { 
      opacity: 1, 
      y: 0, 
      transition: { 
        duration: 0.8, 
        ease: [0.25, 1, 0.5, 1] as any 
      } 
    }
  };

  return (
    <motion.div 
      initial={{ opacity: 0 }} 
      animate={{ opacity: 1 }} 
      exit={{ opacity: 0 }}
      className="relative min-h-screen w-full bg-[#FFF2EC] text-[#1a1a1a] pb-20 overflow-x-hidden"
    >
      {/* SYNAPSE CONNECTION BACKGROUND EFFECT */}
      <div className="absolute inset-0 pointer-events-none z-0 overflow-hidden">
        <svg className="w-full h-full opacity-[0.08]" viewBox="0 0 1400 1000">
          <defs>
            <filter id="glow">
              <feGaussianBlur stdDeviation="2" result="coloredBlur"/>
              <feMerge>
                <feMergeNode in="coloredBlur"/>
                <feMergeNode in="SourceGraphic"/>
              </feMerge>
            </filter>
          </defs>
          
          {/* Nodes (Employees & Software) */}
          {[...Array(20)].map((_, i) => (
            <circle 
              key={`node-${i}`}
              cx={Math.random() * 1400} 
              cy={Math.random() * 1000} 
              r="2" 
              fill={i % 2 === 0 ? "#C5A059" : "#E21E3F"}
            />
          ))}

          {/* Connections (Synapses) */}
          <motion.path
            d="M200,200 Q400,100 600,300 T1000,200"
            fill="none"
            stroke="#C5A059"
            strokeWidth="0.5"
            strokeDasharray="1000"
            animate={{ strokeDashoffset: [1000, 0] }}
            transition={{ duration: 10, repeat: Infinity, ease: "linear" }}
          />
          <motion.path
            d="M100,800 Q500,700 800,900 T1300,700"
            fill="none"
            stroke="#E21E3F"
            strokeWidth="0.5"
            strokeDasharray="1000"
            animate={{ strokeDashoffset: [1000, 0] }}
            transition={{ duration: 12, repeat: Infinity, ease: "linear", delay: 2 }}
          />
        </svg>

        {/* Floating Technical Label */}
        <div className="absolute top-[20%] right-[10%] font-mono text-[9px] text-black/10 uppercase tracking-[0.5em] rotate-90 origin-right">
          [ PILLAR_06 // BEHAVIORAL_ENG_V.6 ]
        </div>
      </div>

      <div className="max-w-[1400px] mx-auto px-6 md:px-12 lg:px-20 relative z-10 pt-32">
        
        {/* NAVIGATION & MONO LABEL */}
        <div className="flex justify-between items-center mb-16">
          <div className="flex items-center gap-6">
            <button 
              onClick={onBack}
              className="group flex items-center gap-3 font-mono text-[10px] uppercase tracking-[0.3em] hover:text-[#C5A059] transition-colors"
            >
              <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
              [ ARCHITECTURE OVERVIEW )
            </button>
            <span className="font-mono text-[10px] text-black/20 uppercase tracking-[0.3em]">/ PILLAR_06</span>
          </div>
          <div className="font-mono text-[9px] text-black/40 uppercase tracking-[0.4em]">
            [ ADOPTION_ENGINE // V.6 ]
          </div>
        </div>

        {/* HERO SECTION */}
        <section className="mb-40">
          <motion.div initial="hidden" whileInView="visible" viewport={{ once: true }} variants={revealVariants as any}>
            <span className="font-mono text-xs text-[#E21E3F] tracking-[0.4em] mb-6 block uppercase">/ Behavioral_Adoption_Architecture</span>
            <h1 className="font-serif text-6xl md:text-8xl lg:text-[8.5rem] leading-[0.9] tracking-tighter mb-10">
              The Human <br />
              <span className="italic text-[#C5A059]">Bridge</span> <br />
              to the Machine.
            </h1>
            <p className="font-sans text-xl md:text-2xl font-light text-[#1a1a1a]/70 max-w-3xl leading-relaxed border-l border-black/20 pl-8">
              Technology is easy. People are hard. We don’t just install software; we engineer the behavioral shift required to actually use it.
            </p>
          </motion.div>
        </section>

        {/* PHILOSOPHY BLOCK */}
        <section className="mb-40 grid grid-cols-1 lg:grid-cols-12 gap-16 items-center">
          <div className="lg:col-span-7">
            <motion.div initial="hidden" whileInView="visible" viewport={{ once: true }} variants={revealVariants as any}>
              <h2 className="font-serif text-4xl md:text-5xl mb-8 italic italic">Shelfware is the Enemy.</h2>
              <div className="space-y-6 text-lg text-black/60 font-light leading-relaxed max-w-2xl">
                <p>There is a massive chasm—The Usage Gap—between what your software is capable of and what your team actually does with it. Most digital transformations fail not because of the code, but because of tech rejection.</p>
                <p className="font-serif text-2xl text-[#1a1a1a] italic border-b border-[#C5A059]/30 pb-4 inline-block">
                  "We sell insurance against technology rejection."
                </p>
                <p>We treat adoption as an engineering problem. We bridge the gap with high-fidelity media, micro-learning, and 24/7 agentic support.</p>
              </div>
            </motion.div>
          </div>
          <div className="lg:col-span-5 relative flex flex-col items-center justify-center p-12 bg-white border border-black/5 shadow-inner">
             <div className="w-full aspect-square border-2 border-dashed border-black/5 rounded-full flex items-center justify-center relative">
                <Users className="w-24 h-24 text-[#E21E3F] stroke-[1]" />
                <motion.div 
                   className="absolute inset-0 rounded-full border-4 border-[#C5A059]/20"
                   animate={{ scale: [1, 1.1, 1], opacity: [0.2, 0.5, 0.2] }}
                   transition={{ duration: 4, repeat: Infinity }}
                />
             </div>
             <div className="mt-8 font-mono text-[9px] text-black/40 tracking-[0.3em] uppercase">
                HUMAN_CENTERED_PROTOCOL... [ ENGAGED ]
             </div>
          </div>
        </section>

        {/* SERVICE MODULES */}
        <section className="mb-40">
          <div className="border-t border-black/10 pt-20 mb-16 flex flex-col md:flex-row justify-between items-end gap-6">
            <h2 className="font-serif text-5xl italic">Adoption Modules.</h2>
            <span className="font-mono text-[10px] text-black/40 uppercase tracking-widest">/ BEHAVIORAL_SUCCESS_STATIONS</span>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-1 bg-black/5 border border-black/5">
            {serviceModules.map((mod) => (
              <motion.div 
                key={mod.id}
                initial="hidden" 
                whileInView="visible" 
                viewport={{ once: true }} 
                variants={revealVariants as any}
                className="bg-[#FFF2EC] p-10 flex flex-col justify-between hover:bg-white transition-colors duration-500 group"
              >
                <div>
                  <span className="font-mono text-[9px] text-[#E21E3F] mb-8 block tracking-widest uppercase">{mod.id}</span>
                  <mod.icon className="w-8 h-8 mb-6 text-black/20 group-hover:text-[#C5A059] transition-colors" />
                  <h3 className="font-serif text-3xl mb-4 leading-none">{mod.title}</h3>
                  <p className="font-sans text-sm text-black/50 leading-relaxed">{mod.desc}</p>
                </div>
                <div className="mt-12 pt-8 border-t border-black/5">
                   <button className="flex items-center gap-2 font-mono text-[9px] uppercase tracking-widest text-[#C5A059]">
                      System Specs <Zap className="w-3 h-3" />
                   </button>
                </div>
              </motion.div>
            ))}
          </div>
        </section>

        {/* 5-DAY SPRINT ROADMAP */}
        <section className="mb-40 py-24 bg-[#1a1a1a] text-white px-10 relative overflow-hidden">
          <div className="absolute top-0 right-0 p-8 opacity-5">
             <Map className="w-64 h-64" />
          </div>
          <div className="max-w-xl mb-16 relative z-10">
            <span className="font-mono text-[10px] text-[#C5A059] tracking-widest uppercase block mb-4">/ ADOPTION_VELOCITY</span>
            <h2 className="font-serif text-5xl mb-6 italic">The 5-Day Sprint.</h2>
            <p className="font-sans text-white/50 leading-relaxed">We don't do "Culture Workshops." We engineer assets that change how your team operates in real-time.</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-0 border border-white/10 relative z-10">
            {sprintRoadmap.map((step) => (
              <div key={step.day} className="p-8 border-r border-white/10 last:border-0 hover:bg-white/5 transition-colors group">
                <span className="font-mono text-[9px] text-[#C5A059] group-hover:text-white transition-colors">DAY {step.day}</span>
                <h4 className="font-serif text-2xl mt-4 mb-2">{step.title}</h4>
                <p className="font-sans text-[11px] text-white/40 leading-relaxed">{step.task}</p>
              </div>
            ))}
          </div>
        </section>

        {/* RETAINER PROTOCOLS */}
        <section className="mb-32 grid grid-cols-1 lg:grid-cols-12 gap-16 pt-20 border-t border-black/10">
          <div className="lg:col-span-5">
            <span className="font-mono text-[10px] text-[#E21E3F] tracking-widest uppercase block mb-4">/ KNOWLEDGE_ASSURANCE</span>
            <h2 className="font-serif text-5xl italic leading-tight">Adoption <br />Continuity.</h2>
            <p className="font-sans text-lg text-black/50 mt-6 leading-relaxed">Business evolves. Your software updates. Our retainers ensure your knowledge assets and AI support agents stay in sync with your reality.</p>
          </div>
          <div className="lg:col-span-7 grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="p-10 border border-black/10 bg-white shadow-sm hover:border-[#C5A059] transition-colors group">
              <Activity className="w-10 h-10 text-[#C5A059] mb-8 group-hover:animate-pulse" />
              <h4 className="font-serif text-2xl mb-4">Content Refresh</h4>
              <p className="font-sans text-sm text-black/50 leading-relaxed">Quarterly updates to your "Company Spotify" and Micro-learning matrix to reflect internal process shifts.</p>
            </div>
            <div className="p-10 bg-[#1a1a1a] text-white group">
              <CheckCircle2 className="w-10 h-10 text-[#E21E3F] mb-8" />
              <h4 className="font-serif text-2xl mb-4">Analyst Calibration</h4>
              <p className="font-sans text-white/50 text-sm leading-relaxed">Ongoing fine-tuning of the Adoption AI agent to ensure 100% accuracy in answering staff queries.</p>
            </div>
          </div>
        </section>

        <div className="py-12 border-t border-black/10 flex items-center justify-between gap-4">
          <div className="flex items-center gap-4">
            <CheckCircle2 className="w-5 h-5 text-[#C5A059]" />
            <span className="font-mono text-[10px] uppercase tracking-widest text-black/40">BEHAVIORAL_ENGINE_ACTIVE // USAGE_GAP_CLOSED</span>
          </div>
          <button onClick={onBack} className="font-mono text-[10px] uppercase tracking-[0.4em] text-[#E21E3F] hover:underline underline-offset-4">
            Return to HQ
          </button>
        </div>
      </div>
    </motion.div>
  );
};

export default Pillar6;